version: '3'
services:
   db:
     image: mariadb
     restart: always
     volumes:
       - dbdata:/var/lib/mysql 
       
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - wpdata:/var/www/html
     restart: always
     env_files:
       - wpenv
        
volumes:
  dbdata:
  wpdata:

networks:
  default:
    external:
      name: nginx-proxy

